### ISSUE TITLE
Fork Status

### ISSUE THREAD

**Issue by robshep** [zalando-zmon/kairosdb#159]
Hi,

Apologies for the possible abuse of this fork's issue tracker but I just wanted to ask about the current state and possible future of this fork of Kairos, and couldn't see a better public channel.

Looking at the network, and the commit history, it seems this fork is receiving a lot of updates, but has diverged a reasonable amount from the original.

If I may ask: is there a significant change in this fork that - for someone looking to start experimenting and integrating with kairosdb - we might be better off looking at this one (Hey, it's got a Dockerfile!! :+1: ) 

Or do you think the changes are so heavily angled towards your ZMON platform it wouldn't be worth looking at, or some other inherant risks)

Please feel free to delete this ( and email back ;) )

Thanks.

Rob

**Comment by alexkorotkikh** [comment]
Hey @robshep,

Thanks for the interest in our KairosDB fork! 

I'd say that most of the features we've introduced are dependent a lot on our platform, and can't be used as-is without it. So if you do not plan to adopt ZMON (wink) I think it will be more suitable for you to go with an upstream.
