### ISSUE TITLE
Clean filesystem cache

### ISSUE THREAD

**Issue by mohabusama** [zalando-zmon/kairosdb#52]
Query cache cleanup is disabled, leading to full disks and degradation of service.

Grafana requests are sent with ``cache: 0``, which skips the query cache

We might need to either:

- Enable query cache cleanup
- Disable query cache completely

**Comment by beverage** [comment]
@mohabusama @vibhory2j Wasn't this done already?  Please close if so.

**Comment by vibhory2j** [comment]
This was addressed as part of https://github.com/zalando-zmon/kairosdb/pull/53. Hence this can be closed.
